DECLARE @N1 INT, @N2 INT, @N3 INT; DECLARE @MAI_MARE INT;
SET @N1 = 60 * RAND();
SET @N2 = 60 * RAND();
SET @N3 = 60 * RAND();

SET @MAI_MARE = CASE WHEN @N1 > @N2 THEN @N1 ELSE @N2 END
SET @MAI_MARE = CASE WHEN @MAI_MARE > @N3 THEN @MAI_MARE ELSE @N3 END

PRINT @N1;
PRINT @N2;
PRINT @N3;
PRINT 'Mai mare = ' + CAST(@MAI_MARE AS VARCHAR(2));