USE AdventureWorks2017;
GO

-- User1
-- CREATE LOGIN User1 WITH PASSWORD = '<very!str0ngpwd>'
-- CREATE USER User1 FROM LOGIN User1;

GRANT SELECT, UPDATE ON SCHEMA :: HumanResources TO User1;

-- User2
-- CREATE LOGIN User2 WITH PASSWORD = '<very!str0ngpwd>'
-- CREATE USER User2 FROM LOGIN User2;

GRANT SELECT ON SCHEMA :: Sales TO User2;

-- User3
-- CREATE LOGIN User3 WITH PASSWORD = '<very!str0ngpwd>'
-- CREATE USER User3 FROM LOGIN User3;

GRANT CREATE DATABASE TO User3;